pages:
  script:
  - mkdir .public
  - mkdir .public/html
  - cp -r static/html/pages .public/html
  - mkdir .public/src
  - cp -r static/src/css .public/src
  - cp -r static/src/zzz .public/src
  - cp -r static/pub/img .public/src
  # - cp -r static/pub/fonts .public/src
  - mkdir .public/pub
  - cp -r static/pub/js .public/pub
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - gitlab-ci

