# Aplication Base Data

APP:
  title: 'App Title'
  lang: 'uk'
  screen:
    sm: 425
    md: 768
    lg: 1024
    xl: 1280
  styles:
    - 'root'
    - 'bs'
    - 'common'
  scripts:
    - 'develop/misc'
  # preload:
  #   img:
  #     # - src: 'single.svg'
  #     #   src1x: '1x.svg'
  #     #   src2x: '@2x.svg'
  #     #   src3x: '@3x.svg'
  #     - src1x: 'cursor/default.png'
  #       src2x: 'cursor/default@2x.png'
  #       # src3x: 'cursor/default@3x.png'


PAGES:
  index:
    no: '00'
    id: 'index'
    styles:
      - 'common'

  home:
    isPublic: false
    isCritical: false
    no: '01'
    id: 'home'
    title: 'Page Title'
    # styles:
    #   - 'customs/'
    # scripts:
    #   - 'common'
    # preload:
    #   img:
    #     - src: 'file.svg'
    #       src1x: '1x.jpg'
    #       src2x: '@2x.jpg'
    #       src3x: '@3x.jpg'

  # publication:
  #   isCritical: false
  #   no: '02'
  #   id: 'publication'
  #   title: 'Page Title'
  #   scripts:
  #     - 'referrer'
  #     - 'ticker'
  #   type:
  #     - name: '_Combined'
  #       isPublic: true
  #       # scripts:
  #       #   - 'fileName'
  #       # isCombined: true

  #     - name: 'Base'
  #       isPublic: true
  #       # scripts:
  #       #   - 'fileName'


## Devel

#* credits: https://stackoverflow.com/questions/9043551/regex-that-matches-integers-only
regexInteger: '/^\d+$/'
